ai:
    agent:
        # Agent configuration
        # see https://symfony.com/doc/current/ai/bundles/ai-bundle.html

        review_assistant:
            model:
                name: "gpt-5-nano"
                capabilities:
                    - !php/const 'Symfony\AI\Platform\Capability::OUTPUT_STRUCTURED'
            prompt: |
                Analyzuj túto zákaznícku recenziu.
                - Urči sentiment (positive, neutral, negative).
                - Identifikuj, či je hlavným problémom samotný produkt (true/false).
                - Prelož text recenzie do potrebných jazykov. Ak je zdrojový jazyk zhodný s cieľovým, vráť pôvodný text.
            tools: false

    store:
        # Store configuration

        # chromadb:
        #    default:
        #        client: 'client.service.id'
        #        collection: 'my_collection'
